### ISSUE TITLE
Fedora 22 - Error after login following restart

### ISSUE THREAD

**Issue by arehtykitna** [raveit65/mate-disk-utility#5]
As discussed on FedoraForum pm,

I had a mate-disk-utility version 1.8.0-3.fc22 (x84_64) error just now after applying updates (FEDORA-2015-10337) from updates-testing to my notebook and restarting. The message came up directly after logging on.

error report dumps:

https://dl.dropbox.com/s/n7n37cfpoc21ywz/ccpp-2015-06-22-21%3A57%3A33-1586.tar.gz?dl=1

This is bare metal install on my notebook.

Cheers,

Mike

**Comment by NiceandGently** [comment]
can you run 'abrt-action-analyze-ccpp-local' in abrt folder, please?
To create a backtrace file.

**Comment by arehtykitna** [comment]
Yeah, try this new version. I should have left it until morning...

https://dl.dropbox.com/s/n7n37cfpoc21ywz/ccpp-2015-06-22-21%3A57%3A33-1586.tar.gz?dl=1

**Comment by NiceandGently** [comment]
Ok, what i see in backtrace is that /usr/libexec/mdu-notification-daemon crashed or created the alarm, which is in autostart.
Does the happens with every login to session or was it only a one shot?

**Comment by arehtykitna** [comment]
Hi, the count is at 4 occurrences now. So yes it is repeating unfortunately.
On 23 Jun 2015 09:37, No_name <notifications@github.com> wrote:Ok, what i see in backtrace is that /usr/libexec/mdu-notification-daemon crashed or created the alarm, which is in autostart.
Does the happens with every login to session or was it only a one shot?

**Comment by NiceandGently** [comment]
Ok,
here in mate gtk3 on bare metal i don't have this issue.
I need to check this with gtk2 version.
For the moment you can disable mdu-notification-daemon in mate-session-properties to avoid anoying abrt popups.
This daemon warns you only for less disk space.

**Comment by arehtykitna** [comment]
this issue is so old a family of mice have moved in, so if it's okay with you Wolfgang I'll close it ;)
